export const resMenu = [
  {
    title: "Recommended",
    itemCards: [
      {
        card: {
          "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
          info: {
            id: "130391318",
            name: "Delhi Tikki Sandwich + Side + Coke",
            category: "SUPER SAVER COMBOS - SAVE UPTO 46%",
            description:
              "Enjoy your favourite Grills sandwich with a choice of drink and a cookie or veg kebabs.",
            imageId: "3b1bb2e4ab7a6f145d675e811b4ee0a3",
            inStock: 1,
            isVeg: 1,
            price: 27900,

            addons: [
              {
                groupId: "127783112",
                groupName: "Choose from Sub",
                choices: [
                  {
                    id: "109192592",
                    name: "Delhi Tikki 15cm",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
              },
              {
                groupId: "127783113",
                groupName: "Choice of Bread",
                choices: [
                  {
                    id: "109192572",
                    name: "White Italian",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109192573",
                    name: "Multigrain",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455587",
                    name: "Multigrain Honey Oats",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455578",
                    name: "Roasted Garlic",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455581",
                    name: "Parmesan Oregano",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
              },
              {
                groupId: "127783114",
                groupName: "Choose From Add Ons",
                choices: [
                  {
                    id: "109192606",
                    name: "Potato Roastie Patty",
                    price: 6000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109192593",
                    name: "Cheese Pull (Mozzarella)",
                    price: 4762,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109192574",
                    name: "Cheese Slice",
                    price: 2860,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
              },

              {
                groupId: "128273437",
                groupName: "Steal Deals @99 (Save upto 34%)",
                choices: [
                  {
                    id: "63207629",
                    name: "2 Pc Oatmeal Raisin Cookies (SAVE upto Rs51)",
                    price: 9900,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "63207627",
                    name: "2 Pc Dark Chunk Choc Cookies (SAVE upto Rs51)",
                    price: 9900,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "63207628",
                    name: "2 Pc Double Dark Choc Cookies (SAVE upto Rs51)",
                    price: 9900,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "63207631",
                    name: "Chicken Meatball - 5 Pc (SAVE upto Rs40).",
                    price: 9900,
                    inStock: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "63207630",
                    name: "Veg Kebab - 5 Pc (SAVE upto Rs30).",
                    price: 9900,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455564",
                    name: "Crispers - Try New (SAVE Rs30)",
                    price: 9900,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
                maxAddons: 6,
                maxFreeAddons: -1,
              },
            ],
            itemAttribute: {
              vegClassifier: "VEG",
            },
            defaultPrice: 27900,
            ribbon: {},
            showImage: true,
            itemBadge: {},
            badgesV2: {},
            ratings: {
              aggregatedRating: {
                rating: "4.0",
                ratingCount: "5 ratings",
                ratingCountV2: "5",
              },
            },
          },
          analytics: {},
          hideRestaurantDetails: true,
        },
      },
      {
        card: {
          "@type": "type.googleapis.com/swiggy.presentation.food.v2.Dish",
          info: {
            id: "130391320",
            name: "Bombay Grill Sandwich + Side + Coke",
            category: "SUPER SAVER COMBOS - SAVE UPTO 46%",
            description:
              "Enjoy your favourite Grills sandwich with a choice of drink and a cookie or veg kebabs.",
            imageId: "6f6f6cdda05e7a857f18bd8459f231ce",
            inStock: 1,
            isVeg: 1,
            price: 28900,
            variants: {},
            variantsV2: {},
            addons: [
              {
                groupId: "127783117",
                groupName: "Choose from Sub",
                choices: [
                  {
                    id: "109192591",
                    name: "Bombay Grill 15cm",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
                maxAddons: 1,
                maxFreeAddons: -1,
                minAddons: 1,
              },
              {
                groupId: "127783118",
                groupName: "Choice of Bread",
                choices: [
                  {
                    id: "109192572",
                    name: "White Italian",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109192573",
                    name: "Multigrain",
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455587",
                    name: "Multigrain Honey Oats",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455578",
                    name: "Roasted Garlic",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                  {
                    id: "109455581",
                    name: "Parmesan Oregano",
                    price: 1000,
                    inStock: 1,
                    isVeg: 1,
                    isEnabled: 1,
                  },
                ],
                maxAddons: 1,
                maxFreeAddons: -1,
                minAddons: 1,
              },
            ],
          },
        },
      },
    ],
  },
];
